name: Update AFL Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install dependencies
      run: |
        install.packages(c("fitzRoy"), repos = "https://cloud.r-project.org")
      shell: Rscript {0}
      
    - name: Run R script
      run: Rscript update_afl_data.R
      
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Update AFL data" || exit 0
        git push

    - name: Upload CSVs to PythonAnywhere
      env:
        PYTHONANYWHERE_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: Token $PYTHONANYWHERE_TOKEN" \
          -F "content=@afl_match_results.csv" \
          https://www.pythonanywhere.com/api/v0/user/testingafl/files/path/home/testingafl/afl_ranking_system/afl_match_results.csv
        curl -X POST \
          -H "Authorization: Token $PYTHONANYWHERE_TOKEN" \
          -F "content=@afl_match_results_concise.csv" \
          https://www.pythonanywhere.com/api/v0/user/testingafl/files/path/home/testingafl/afl_ranking_system/afl_match_results_concise.csv

    - name: Update database on PythonAnywhere
      env:
        PYTHONANYWHERE_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
      run: |
        response=$(curl -X POST \
          -H "Authorization: Token $PYTHONANYWHERE_TOKEN" \
          https://www.pythonanywhere.com/api/v0/user/testingafl/consoles/ \
          -d "executable=/home/testingafl/afl_ranking_system/venv/bin/python" \
          -d "arguments=/home/testingafl/afl_ranking_system/update_database.py" \
          -d "working_directory=/home/testingafl/afl_ranking_system")
        echo "Response: $response"
        if [[ $response != *"200"* ]]; then
          echo "Failed to start console task"
          exit 1
        fi
